services:
  prepac:
    build: .
    container_name: prepac
    ports:
      - "1234:1234"
    environment:
      PREPAC_LOG_LEVEL: INFO
      PREPAC_LOG_JSON: "false"
    volumes:
      - ./config:/config
      - ./data/tv:/media/tv
      - ./data/movies:/media/movies
      - ./data/youtube:/media/youtube
      - ./data/destination:/media/dest
    restart: unless-stopped
    stop_grace_period: 45s
