APP_NAME = "PrepaC"
APP_VERSION = "1.0.0"
BUILD_NUMBER = "dev"
FULL_VERSION = f"{APP_VERSION}+{BUILD_NUMBER}"
DISPLAY_VERSION = f"{APP_NAME} v{APP_VERSION} (Build {BUILD_NUMBER})"
BUILD_DISPLAY = BUILD_NUMBER
